In [1]:
import numpy as np
import tensorflow as tf

In [12]:
# 二维卷积层，互相关运算
def coord(X, K):
    h, w = K.shape
    Y = tf.Variable(tf.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1)))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j].assign(tf.cast(tf.reduce_sum(X[i: i + h, j: j + w] * K), dtype=tf.float32))
    return Y

In [13]:
X = tf.constant([[1,2,3], [3,4,5], [4,5,6]])
K = tf.constant([[1,2],[3,4]])
Y = coord(X,K)

In [14]:
Y

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[30., 40.],
       [43., 53.]], dtype=float32)>

In [17]:
# 填充、步幅
# 多通道

def corr2d(X, K):
    h, w = K.shape
    if len(X.shape) <= 1:
        X = tf.reshape(X, (X.shape[0],1))
    Y = tf.Variable(tf.zeros((X.shape[0] - h + 1, X.shape[1] - w +1)))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i,j].assign(tf.cast(tf.reduce_sum(X[i:i+h, j:j+w] * K), dtype=tf.float32))
    return Y

def corr2d_multi_in(X, K):
    return tf.reduce_sum([corr2d(X[i], K[i]) for i in range(X.shape[0])],axis=0)

X = tf.constant([[[0,1,2],[3,4,5],[6,7,8]],
                 [[1,2,3],[4,5,6],[7,8,9]]])
K = tf.constant([[[0,1],[2,3]],
                 [[1,2],[3,4]]])

In [18]:
corr2d_multi_in(X, K)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 56.,  72.],
       [104., 120.]], dtype=float32)>

In [19]:
K = tf.stack([K, K+1, K+2],axis=0)
K

<tf.Tensor: shape=(3, 2, 2, 2), dtype=int32, numpy=
array([[[[0, 1],
         [2, 3]],

        [[1, 2],
         [3, 4]]],


       [[[1, 2],
         [3, 4]],

        [[2, 3],
         [4, 5]]],


       [[[2, 3],
         [4, 5]],

        [[3, 4],
         [5, 6]]]], dtype=int32)>